apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.secret.username | b64enc }}
  mongo-root-password: {{ .Values.mongodb.secret.password | b64enc }}
