apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: cm9vdA== # base64 encoded value for 'root'
  mongo-root-password: ZXhhbXBsZQ== # base64 encoded value for 'example'
