Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
  
    # Master node configuration
    config.vm.define "master" do |master|
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "10.0.0.10", virtualbox__intnet: false
      master.ssh.insert_key = true
      master.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-master"
        vb.memory = "2048"
        vb.cpus = 2
      end
      master.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
      SHELL
    end
  
    # Worker nodes configuration
    (1..2).each do |i|
      config.vm.define "worker#{i}" do |worker|
        worker.vm.hostname = "worker#{i}"
        worker.vm.network "private_network", ip: "10.0.0.1#{i}", virtualbox__intnet: false
        worker.ssh.insert_key = true
        worker.vm.provider "virtualbox" do |vb|
          vb.name = "k8s-worker#{i}"
          vb.memory = "1048"
          vb.cpus = 1
        end
        worker.vm.provision "shell", inline: <<-SHELL
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
        SHELL
      end
    end
  
    # Ansible provisioning
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
      ansible.sudo = true
      ansible.inventory_path = "hosts.ini"
    end
  end