IMAGE_NAME = "bento/ubuntu-20.04"
NUMERO_NODI = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.boot_timeout = 3000
    config.vbguest.auto_update = false


    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.provider "virtualbox" do |vb|
          vb.name = "master"
          vb.memory = 2048
          vb.cpus = 2
          vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        end
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "master-playbook.yml"
        end
    end

    (1..NUMERO_NODI).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "10.0.0.1#{i}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "node-playbook.yml"
            end
            node.vm.provider "virtualbox" do |vb|
              vb.memory = 1024
              vb.cpus = 1
              vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
            end
        end
    end
end

