Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
  

  # Ansible control machine configuration
  config.vm.define "ansible-control" do |control|
    control.vm.hostname = "ansible-control"
    control.vm.network "private_network", ip: "10.0.0.4"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-control"
      vb.memory = "1024"
      vb.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip ansible
    SHELL
  end

  # Master node configuration
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "10.0.0.10"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-master"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Worker node 1 configuration
  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: "10.0.0.11"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-worker1"
      vb.memory = "1048"
      vb.cpus = 1
    end
  end

  # Worker node 2 configuration
  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"
    worker.vm.network "private_network", ip: "10.0.0.12"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-worker2"
      vb.memory = "1048"
      vb.cpus = 1
    end
  end
end