---
- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Ensure ext4 filesystem is present
      filesystem:
        fstype: ext4
        dev: /dev/sda1

    - name: Ensure directory /var/lib/kubelet exists
      file:
        path: /var/lib/kubelet
        state: directory
        owner: root
        group: root
        mode: '0755'

- hosts: master
  become: true
  tasks:
    - name: Ensure directory /var/lib/etcd exists
      file:
        path: /var/lib/etcd
        state: directory
        owner: root
        group: root
        mode: '0755'