---
- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - socat
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt package index after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Check if swap is enabled
      set_fact:
        swap_enabled: "{{ ansible_swaptotal_mb > 0 }}"

    - name: Disable SWAP since Kubernetes can't work with swap enabled (1/2)
      command: swapoff -a
      when: swap_enabled
      changed_when: swap_enabled

    - name: Disable SWAP in fstab since Kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      register: fstab_update
      changed_when: fstab_update.changed
      when: swap_enabled

    - name: Print swap status
      debug:
        msg: "Swap has been disabled."
      when: swap_enabled

    - name: Ensure ext4 filesystem is present
      filesystem:
        fstype: ext4
        dev: /dev/sda1

    - name: Ensure directory /var/lib/kubelet exists
      file:
        path: /var/lib/kubelet
        state: directory
        owner: root
        group: root
        mode: '0755'

- hosts: master
  become: true
  tasks:
    - name: Ensure directory /var/lib/etcd exists
      file:
        path: /var/lib/etcd
        state: directory
        owner: root
        group: root
        mode: '0755'
