services:
  frontend:
    image: safred89/frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: safred89/backend-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://root:example@mongodb:27017/mydatabase?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
